# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go generate ./...
    - tsc --project web
builds:
  - main: ./cmd/seekr-cli/main.go
    id: "seekr-cli"
    binary: seekr-cli
    goos:
      - linux
      - windows
        #- darwin
        #- freebsd
    goarch:
      - amd64
        #- arm64
    tags:
      - osusergo
      - netgo
      - static_build
    asmflags:
      - -trimpath
    ldflags:
      - -s -w
      - "-X main.version={{ .Version }}"
    env:
      - CGO_ENABLED=0
  - main: ./main.go
    id: "seekr"
    binary: seekr
    goos:
      - linux
      - windows
        #- darwin
        #- freebsd
    goarch:
      - amd64
        #- arm64
    tags:
      - osusergo
      - netgo
      - static_build
    asmflags:
      - -trimpath
    ldflags:
      - -s -w
      - "-X main.version={{ .Version }}"
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm64
archives:
  -
    format: binary
    files:
      - ./result/Seekr.AppImage
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
