name: "Nix flake build"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: ls
    #- run: nix build .#seekr-appimage
    #- name: Upload a Build Artifact
      #uses: actions/upload-artifact@v3.1.2
      #with:
    # Artifact name
        #name: appimage
    # A file, directory or wildcard pattern that describes what to upload
        #path: ./result/
    # The desired behavior if no files are found using the provided path.
    - uses: LouisBrunner/checks-action@v1.6.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Nix build
        conclusion: ${{ job.status }}
        output: |
          {"summary":"${{ steps.test.outputs.summary }}"}
