# Releaser workflow setup
# https://goreleaser.com/ci/actions/
#
name: release

# run only on tags
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
   contents: write # needed to write releases
   id-token: write # needed for keyless signing
   packages: write # needed for ghcr access

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: | ${{ runner.os }}-go-
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build .#appimage
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
      - name: install tsc
        run: npm install -g typescript
      - uses: sigstore/cosign-installer@v2.8.1         # installs cosign
      - uses: goreleaser/goreleaser-action@v4.2.0          # run goreleaser
        with:
          version: latest
          args: release --rm-dist 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
